### ISSUE TITLE
Report has value "Unknown" for assembly in VIP 5.2

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/vip-report#120]
Report has value "Unknown" for assembly in VIP 5.2.0

**Comment by dennishendriksen** [comment]
The default [molgenis/vip-report-template](https://github.com/molgenis/vip-report-template) displays the value of the `assembly` field returned by `api.getHtsFileMetadata()`. [molgenis/vip-report](https://github.com/molgenis/vip-report) populates this field using `org.molgenis.vcf.utils.sample.mapper.HtsFileMapper` from [molgenis/vip-utils](https://github.com/molgenis/vip-utils) which tries to extract the `assembly` value from the [1.4.6 Assembly field](http://samtools.github.io/hts-specs/VCFv4.3.pdf).

According to this specification this field is meant for `Breakpoint assemblies for structural variations may use an external file` and the value is an `url` from which follows that the current implementation is using the wrong field.

Since the `assembly` is not stored in the input .vcf and is not passed as a command-line argument to `vip-report` the value `Unknown` is correct.
